apiVersion: v1
kind: Service
metadata:
  name: queries-serv
spec:
  type: NodePort
  selector:
    app: queries
  ports:
    - name: queries
      protocol: TCP
      port: 5001
      targetPort: 5001
